version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/Toshi

    steps:
      - checkout
      - run:
          name: ktlint
          command: ./gradlew ktlint
          environment:
            TERM: dumb

      - run:
          name: Assemble & Test
          command: ./gradlew testRelease --console=plain
          environment:
            TERM: dumb

      - run:
          name: Migration
          command: bash ./migrationTest.sh
          environment:
            TERM: dumb